/*
 * Shared data for the extension's own pages (side panel + fullscreen).
 * The floating widget is a content script with its own trimmed dictionary —
 * it deliberately does not load this file.
 */

const i18n = {
  uk: {
    eyebrow: "Боковий віджет",
    title: "Фокус Pomodoro",
    modes: {
      work: "Робота",
      shortBreak: "Коротка перерва",
      longBreak: "Довга перерва"
    },
    hints: {
      work: "Зосередься на одній задачі. Усе зайве — після сигналу.",
      shortBreak: "Встань, випий води, розімни очі та плечі.",
      longBreak: "Довша пауза: рух, свіже повітря або чай."
    },
    idleHint: "Натисни «Старт», щоб почати або продовжити.",
    runningSubtitle: "Віджет залишається відкритим у side panel під час переходу між вкладками.",
    idleSubtitle: "Спокійний таймер для фокусу, перерв і задач.",
    start: "Старт",
    pause: "Пауза",
    nextStage: "Наступний етап",
    reset: "Скинути",
    compact: "Менший",
    full: "Повний",
    sessionsTodayLabel: "Сьогодні",
    sessionsSmall: "сесій",
    focusTimeLabel: "Фокус",
    focusSmall: "час",
    goalLabel: "Ціль",
    goalSmall: "сесій",
    tasksTitle: "Задачі",
    clearDone: "Очистити виконані",
    taskPlaceholder: "Додай одну фокус-задачу...",
    emptyTask: "Поки задач немає. Додай одну головну задачу на наступний Pomodoro.",
    markDoneTitle: "Позначити виконаною",
    deleteTaskTitle: "Видалити задачу",
    settingsTitle: "Налаштування",
    resetStats: "Скинути статистику",
    workMinutesLabel: "Робота, хв",
    shortBreakLabel: "Перерва, хв",
    longBreakLabel: "Довга перерва, хв",
    cyclesBeforeLongLabel: "Довга перерва кожні",
    reminderLabel: "Попередження за, сек",
    dailyGoalLabel: "Ціль сесій/день",
    textSizeLabel: "Розмір тексту, %",
    soundStyleLabel: "Стиль звуку",
    soundBright: "Bright clean",
    soundArcade: "Arcade",
    soundBell: "Bell",
    soundSoft: "Soft",
    autoContinueLabel: "Автоматично запускати наступний етап",
    notificationsLabel: "Системні нагадування",
    soundsLabel: "Звукові сигнали",
    floatingWidgetLabel: "Плаваючий віджет поверх сайтів",
    floatingWidgetQuick: "Плаваючий віджет на сайтах",
    widgetStateOn: "Увімк.",
    widgetStateOff: "Вимк.",
    fireflyAnimationLabel: "Анімація світлячків під час фокусу",
    fireflyIntervalLabel: "Світлячки кожні",
    fireflyUnitSeconds: "Секунди",
    fireflyUnitMinutes: "Хвилини",
    themeLabel: "Тема оформлення",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Додати дедлайн",
    deadlineTitle: "Дедлайн задачі",
    saveSettings: "Зберегти налаштування",
    minShort: "хв",
    addTaskAria: "Додати задачу",
    fullscreen: "На весь екран",
    fullscreenTitle: "Відкрити таймер на весь екран",
    enterFullscreen: "Розгорнути на весь екран",
    exitFullscreen: "Вийти з повного екрана",
    close: "Закрити",
    sessionsToday: "сесій сьогодні",
    focusToday: "фокусу сьогодні",
    noTaskYet: "Задачу не обрано"
  },
  en: {
    eyebrow: "Side panel widget",
    title: "Pomodoro Focus",
    modes: {
      work: "Focus",
      shortBreak: "Short break",
      longBreak: "Long break"
    },
    hints: {
      work: "Focus on one task. Everything else can wait until the signal.",
      shortBreak: "Stand up, drink water and relax your eyes and shoulders.",
      longBreak: "A longer pause: move, get fresh air or make tea."
    },
    idleHint: "Press Start to begin or continue.",
    runningSubtitle: "The widget stays open in the side panel while you switch tabs.",
    idleSubtitle: "A calm timer for focus, breaks and tasks.",
    start: "Start",
    pause: "Pause",
    nextStage: "Next stage",
    reset: "Reset",
    compact: "Compact",
    full: "Full",
    sessionsTodayLabel: "Today",
    sessionsSmall: "sessions",
    focusTimeLabel: "Focus",
    focusSmall: "time",
    goalLabel: "Goal",
    goalSmall: "sessions",
    tasksTitle: "Tasks",
    clearDone: "Clear done",
    taskPlaceholder: "Add one focus task...",
    emptyTask: "No tasks yet. Add one main task for the next Pomodoro.",
    markDoneTitle: "Mark as done",
    deleteTaskTitle: "Delete task",
    settingsTitle: "Settings",
    resetStats: "Reset stats",
    workMinutesLabel: "Work, min",
    shortBreakLabel: "Break, min",
    longBreakLabel: "Long break, min",
    cyclesBeforeLongLabel: "Long break every",
    reminderLabel: "Reminder before end, sec",
    dailyGoalLabel: "Daily goal",
    textSizeLabel: "Text size, %",
    soundStyleLabel: "Sound style",
    soundBright: "Bright clean",
    soundArcade: "Arcade",
    soundBell: "Bell",
    soundSoft: "Soft",
    autoContinueLabel: "Automatically start the next stage",
    notificationsLabel: "System notifications",
    soundsLabel: "Sound signals",
    floatingWidgetLabel: "Floating widget on websites",
    floatingWidgetQuick: "Floating widget on sites",
    widgetStateOn: "On",
    widgetStateOff: "Off",
    fireflyAnimationLabel: "Firefly animation during focus",
    fireflyIntervalLabel: "Fireflies every",
    fireflyUnitSeconds: "Seconds",
    fireflyUnitMinutes: "Minutes",
    themeLabel: "Theme",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Add deadline",
    deadlineTitle: "Task deadline",
    saveSettings: "Save settings",
    minShort: "min",
    addTaskAria: "Add task",
    fullscreen: "Fullscreen",
    fullscreenTitle: "Open the timer fullscreen",
    enterFullscreen: "Enter fullscreen",
    exitFullscreen: "Exit fullscreen",
    close: "Close",
    sessionsToday: "sessions today",
    focusToday: "focused today",
    noTaskYet: "No task picked"
  },
  de: {
    eyebrow: "Seitenleisten-Widget",
    title: "Pomodoro Fokus",
    modes: { work: "Fokus", shortBreak: "Kurze Pause", longBreak: "Lange Pause" },
    hints: {
      work: "Konzentriere dich auf eine Aufgabe. Alles andere kann bis zum Signal warten.",
      shortBreak: "Steh auf, trink Wasser und entspanne Augen und Schultern.",
      longBreak: "Eine längere Pause: beweg dich, frische Luft oder ein Tee."
    },
    idleHint: "Drücke „Start“, um zu beginnen oder fortzufahren.",
    runningSubtitle: "Das Widget bleibt in der Seitenleiste offen, während du Tabs wechselst.",
    idleSubtitle: "Ein ruhiger Timer für Fokus, Pausen und Aufgaben.",
    start: "Start",
    pause: "Pause",
    nextStage: "Nächste Phase",
    reset: "Zurücksetzen",
    compact: "Kompakt",
    full: "Voll",
    sessionsTodayLabel: "Heute",
    sessionsSmall: "Sitzungen",
    focusTimeLabel: "Fokus",
    focusSmall: "Zeit",
    goalLabel: "Ziel",
    goalSmall: "Sitzungen",
    tasksTitle: "Aufgaben",
    clearDone: "Erledigte löschen",
    taskPlaceholder: "Eine Fokus-Aufgabe hinzufügen…",
    emptyTask: "Noch keine Aufgaben. Füge eine Hauptaufgabe für den nächsten Pomodoro hinzu.",
    markDoneTitle: "Als erledigt markieren",
    deleteTaskTitle: "Aufgabe löschen",
    settingsTitle: "Einstellungen",
    resetStats: "Statistik zurücksetzen",
    workMinutesLabel: "Arbeit, Min",
    shortBreakLabel: "Pause, Min",
    longBreakLabel: "Lange Pause, Min",
    cyclesBeforeLongLabel: "Lange Pause alle",
    reminderLabel: "Erinnerung vor Ende, Sek",
    dailyGoalLabel: "Tagesziel",
    textSizeLabel: "Textgröße, %",
    soundStyleLabel: "Klangstil",
    soundBright: "Hell & klar",
    soundArcade: "Arcade",
    soundBell: "Glocke",
    soundSoft: "Sanft",
    autoContinueLabel: "Nächste Phase automatisch starten",
    notificationsLabel: "Systembenachrichtigungen",
    soundsLabel: "Tonsignale",
    floatingWidgetLabel: "Schwebendes Widget auf Webseiten",
    floatingWidgetQuick: "Schwebendes Widget auf Seiten",
    widgetStateOn: "An",
    widgetStateOff: "Aus",
    fireflyAnimationLabel: "Glühwürmchen-Animation beim Fokus",
    fireflyIntervalLabel: "Glühwürmchen alle",
    fireflyUnitSeconds: "Sekunden",
    fireflyUnitMinutes: "Minuten",
    themeLabel: "Design",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Frist hinzufügen",
    deadlineTitle: "Aufgabenfrist",
    saveSettings: "Einstellungen speichern",
    minShort: "Min",
    addTaskAria: "Aufgabe hinzufügen",
    fullscreen: "Vollbild",
    fullscreenTitle: "Timer im Vollbild öffnen",
    enterFullscreen: "Vollbild starten",
    exitFullscreen: "Vollbild beenden",
    close: "Schließen",
    sessionsToday: "Sitzungen heute",
    focusToday: "Fokus heute",
    noTaskYet: "Keine Aufgabe gewählt"
  },
  es: {
    eyebrow: "Widget del panel lateral",
    title: "Pomodoro Focus",
    modes: { work: "Enfoque", shortBreak: "Descanso corto", longBreak: "Descanso largo" },
    hints: {
      work: "Concéntrate en una tarea. Todo lo demás puede esperar a la señal.",
      shortBreak: "Levántate, bebe agua y relaja los ojos y los hombros.",
      longBreak: "Una pausa más larga: muévete, toma aire fresco o un té."
    },
    idleHint: "Pulsa «Iniciar» para empezar o continuar.",
    runningSubtitle: "El widget permanece abierto en el panel lateral mientras cambias de pestaña.",
    idleSubtitle: "Un temporizador tranquilo para enfoque, descansos y tareas.",
    start: "Iniciar",
    pause: "Pausa",
    nextStage: "Siguiente etapa",
    reset: "Reiniciar",
    compact: "Compacto",
    full: "Completo",
    sessionsTodayLabel: "Hoy",
    sessionsSmall: "sesiones",
    focusTimeLabel: "Enfoque",
    focusSmall: "tiempo",
    goalLabel: "Meta",
    goalSmall: "sesiones",
    tasksTitle: "Tareas",
    clearDone: "Borrar completadas",
    taskPlaceholder: "Añade una tarea de enfoque…",
    emptyTask: "Aún no hay tareas. Añade una tarea principal para el próximo Pomodoro.",
    markDoneTitle: "Marcar como hecha",
    deleteTaskTitle: "Eliminar tarea",
    settingsTitle: "Ajustes",
    resetStats: "Restablecer estadísticas",
    workMinutesLabel: "Trabajo, min",
    shortBreakLabel: "Descanso, min",
    longBreakLabel: "Descanso largo, min",
    cyclesBeforeLongLabel: "Descanso largo cada",
    reminderLabel: "Aviso antes del final, seg",
    dailyGoalLabel: "Meta diaria",
    textSizeLabel: "Tamaño del texto, %",
    soundStyleLabel: "Estilo de sonido",
    soundBright: "Brillante y limpio",
    soundArcade: "Arcade",
    soundBell: "Campana",
    soundSoft: "Suave",
    autoContinueLabel: "Iniciar automáticamente la siguiente etapa",
    notificationsLabel: "Notificaciones del sistema",
    soundsLabel: "Señales de sonido",
    floatingWidgetLabel: "Widget flotante en los sitios web",
    floatingWidgetQuick: "Widget flotante en sitios",
    widgetStateOn: "Activado",
    widgetStateOff: "Desactivado",
    fireflyAnimationLabel: "Animación de luciérnagas durante el enfoque",
    fireflyIntervalLabel: "Luciérnagas cada",
    fireflyUnitSeconds: "Segundos",
    fireflyUnitMinutes: "Minutos",
    themeLabel: "Tema",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Añadir fecha límite",
    deadlineTitle: "Fecha límite de la tarea",
    saveSettings: "Guardar ajustes",
    minShort: "min",
    addTaskAria: "Añadir tarea",
    fullscreen: "Pantalla completa",
    fullscreenTitle: "Abrir el temporizador a pantalla completa",
    enterFullscreen: "Pantalla completa",
    exitFullscreen: "Salir de pantalla completa",
    close: "Cerrar",
    sessionsToday: "sesiones hoy",
    focusToday: "de enfoque hoy",
    noTaskYet: "Sin tarea elegida"
  },
  it: {
    eyebrow: "Widget del pannello laterale",
    title: "Pomodoro Focus",
    modes: { work: "Concentrazione", shortBreak: "Pausa breve", longBreak: "Pausa lunga" },
    hints: {
      work: "Concentrati su un compito. Tutto il resto può aspettare il segnale.",
      shortBreak: "Alzati, bevi acqua e rilassa occhi e spalle.",
      longBreak: "Una pausa più lunga: muoviti, prendi aria fresca o un tè."
    },
    idleHint: "Premi «Avvia» per iniziare o continuare.",
    runningSubtitle: "Il widget resta aperto nel pannello laterale mentre cambi scheda.",
    idleSubtitle: "Un timer tranquillo per concentrazione, pause e attività.",
    start: "Avvia",
    pause: "Pausa",
    nextStage: "Fase successiva",
    reset: "Reimposta",
    compact: "Compatto",
    full: "Completo",
    sessionsTodayLabel: "Oggi",
    sessionsSmall: "sessioni",
    focusTimeLabel: "Concentrazione",
    focusSmall: "tempo",
    goalLabel: "Obiettivo",
    goalSmall: "sessioni",
    tasksTitle: "Attività",
    clearDone: "Cancella completate",
    taskPlaceholder: "Aggiungi un'attività di concentrazione…",
    emptyTask: "Ancora nessuna attività. Aggiungi un'attività principale per il prossimo Pomodoro.",
    markDoneTitle: "Segna come completata",
    deleteTaskTitle: "Elimina attività",
    settingsTitle: "Impostazioni",
    resetStats: "Azzera statistiche",
    workMinutesLabel: "Lavoro, min",
    shortBreakLabel: "Pausa, min",
    longBreakLabel: "Pausa lunga, min",
    cyclesBeforeLongLabel: "Pausa lunga ogni",
    reminderLabel: "Avviso prima della fine, sec",
    dailyGoalLabel: "Obiettivo giornaliero",
    textSizeLabel: "Dimensione del testo, %",
    soundStyleLabel: "Stile del suono",
    soundBright: "Brillante e pulito",
    soundArcade: "Arcade",
    soundBell: "Campana",
    soundSoft: "Morbido",
    autoContinueLabel: "Avvia automaticamente la fase successiva",
    notificationsLabel: "Notifiche di sistema",
    soundsLabel: "Segnali sonori",
    floatingWidgetLabel: "Widget fluttuante sui siti web",
    floatingWidgetQuick: "Widget fluttuante sui siti",
    widgetStateOn: "Attivo",
    widgetStateOff: "Spento",
    fireflyAnimationLabel: "Animazione di lucciole durante la concentrazione",
    fireflyIntervalLabel: "Lucciole ogni",
    fireflyUnitSeconds: "Secondi",
    fireflyUnitMinutes: "Minuti",
    themeLabel: "Tema",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Aggiungi scadenza",
    deadlineTitle: "Scadenza attività",
    saveSettings: "Salva impostazioni",
    minShort: "min",
    addTaskAria: "Aggiungi attività",
    fullscreen: "Schermo intero",
    fullscreenTitle: "Apri il timer a schermo intero",
    enterFullscreen: "Schermo intero",
    exitFullscreen: "Esci da schermo intero",
    close: "Chiudi",
    sessionsToday: "sessioni oggi",
    focusToday: "di concentrazione oggi",
    noTaskYet: "Nessuna attività scelta"
  },
  sk: {
    eyebrow: "Widget bočného panela",
    title: "Pomodoro Fokus",
    modes: { work: "Sústredenie", shortBreak: "Krátka prestávka", longBreak: "Dlhá prestávka" },
    hints: {
      work: "Sústreď sa na jednu úlohu. Všetko ostatné počká na signál.",
      shortBreak: "Postav sa, napi sa vody a uvoľni oči a ramená.",
      longBreak: "Dlhšia prestávka: pohyb, čerstvý vzduch alebo čaj."
    },
    idleHint: "Stlač „Štart“ pre začatie alebo pokračovanie.",
    runningSubtitle: "Widget zostáva otvorený v bočnom paneli, keď prepínaš karty.",
    idleSubtitle: "Pokojný časovač na sústredenie, prestávky a úlohy.",
    start: "Štart",
    pause: "Pauza",
    nextStage: "Ďalšia fáza",
    reset: "Obnoviť",
    compact: "Kompaktný",
    full: "Plný",
    sessionsTodayLabel: "Dnes",
    sessionsSmall: "relácií",
    focusTimeLabel: "Fokus",
    focusSmall: "čas",
    goalLabel: "Cieľ",
    goalSmall: "relácií",
    tasksTitle: "Úlohy",
    clearDone: "Vymazať hotové",
    taskPlaceholder: "Pridaj jednu úlohu na sústredenie…",
    emptyTask: "Zatiaľ žiadne úlohy. Pridaj jednu hlavnú úlohu pre ďalší Pomodoro.",
    markDoneTitle: "Označiť ako hotové",
    deleteTaskTitle: "Odstrániť úlohu",
    settingsTitle: "Nastavenia",
    resetStats: "Vynulovať štatistiky",
    workMinutesLabel: "Práca, min",
    shortBreakLabel: "Prestávka, min",
    longBreakLabel: "Dlhá prestávka, min",
    cyclesBeforeLongLabel: "Dlhá prestávka každých",
    reminderLabel: "Upozornenie pred koncom, s",
    dailyGoalLabel: "Denný cieľ",
    textSizeLabel: "Veľkosť textu, %",
    soundStyleLabel: "Štýl zvuku",
    soundBright: "Jasný čistý",
    soundArcade: "Arkáda",
    soundBell: "Zvonček",
    soundSoft: "Jemný",
    autoContinueLabel: "Automaticky spustiť ďalšiu fázu",
    notificationsLabel: "Systémové upozornenia",
    soundsLabel: "Zvukové signály",
    floatingWidgetLabel: "Plávajúci widget na weboch",
    floatingWidgetQuick: "Plávajúci widget na weboch",
    widgetStateOn: "Zap.",
    widgetStateOff: "Vyp.",
    fireflyAnimationLabel: "Animácia svetlušiek počas sústredenia",
    fireflyIntervalLabel: "Svetlušky každých",
    fireflyUnitSeconds: "Sekundy",
    fireflyUnitMinutes: "Minúty",
    themeLabel: "Téma",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Pridať termín",
    deadlineTitle: "Termín úlohy",
    saveSettings: "Uložiť nastavenia",
    minShort: "min",
    addTaskAria: "Pridať úlohu",
    fullscreen: "Na celú obrazovku",
    fullscreenTitle: "Otvoriť časovač na celú obrazovku",
    enterFullscreen: "Na celú obrazovku",
    exitFullscreen: "Ukončiť celú obrazovku",
    close: "Zavrieť",
    sessionsToday: "relácií dnes",
    focusToday: "sústredenia dnes",
    noTaskYet: "Nevybraná úloha"
  },
  cs: {
    eyebrow: "Widget bočního panelu",
    title: "Pomodoro Fokus",
    modes: { work: "Soustředění", shortBreak: "Krátká přestávka", longBreak: "Dlouhá přestávka" },
    hints: {
      work: "Soustřeď se na jeden úkol. Všechno ostatní počká na signál.",
      shortBreak: "Postav se, napij se vody a uvolni oči a ramena.",
      longBreak: "Delší pauza: pohyb, čerstvý vzduch nebo čaj."
    },
    idleHint: "Stiskni „Start“ pro zahájení nebo pokračování.",
    runningSubtitle: "Widget zůstává otevřený v bočním panelu, když přepínáš karty.",
    idleSubtitle: "Klidný časovač pro soustředění, přestávky a úkoly.",
    start: "Start",
    pause: "Pauza",
    nextStage: "Další fáze",
    reset: "Obnovit",
    compact: "Kompaktní",
    full: "Plný",
    sessionsTodayLabel: "Dnes",
    sessionsSmall: "relací",
    focusTimeLabel: "Fokus",
    focusSmall: "čas",
    goalLabel: "Cíl",
    goalSmall: "relací",
    tasksTitle: "Úkoly",
    clearDone: "Smazat hotové",
    taskPlaceholder: "Přidej jeden úkol k soustředění…",
    emptyTask: "Zatím žádné úkoly. Přidej jeden hlavní úkol pro další Pomodoro.",
    markDoneTitle: "Označit jako hotové",
    deleteTaskTitle: "Smazat úkol",
    settingsTitle: "Nastavení",
    resetStats: "Vynulovat statistiky",
    workMinutesLabel: "Práce, min",
    shortBreakLabel: "Přestávka, min",
    longBreakLabel: "Dlouhá přestávka, min",
    cyclesBeforeLongLabel: "Dlouhá přestávka každých",
    reminderLabel: "Upozornění před koncem, s",
    dailyGoalLabel: "Denní cíl",
    textSizeLabel: "Velikost textu, %",
    soundStyleLabel: "Styl zvuku",
    soundBright: "Jasný čistý",
    soundArcade: "Arkáda",
    soundBell: "Zvonek",
    soundSoft: "Jemný",
    autoContinueLabel: "Automaticky spustit další fázi",
    notificationsLabel: "Systémová oznámení",
    soundsLabel: "Zvukové signály",
    floatingWidgetLabel: "Plovoucí widget na webech",
    floatingWidgetQuick: "Plovoucí widget na webech",
    widgetStateOn: "Zap.",
    widgetStateOff: "Vyp.",
    fireflyAnimationLabel: "Animace světlušek při soustředění",
    fireflyIntervalLabel: "Světlušky každých",
    fireflyUnitSeconds: "Sekundy",
    fireflyUnitMinutes: "Minuty",
    themeLabel: "Motiv",
    themeMidnight: "Midnight",
    themeDaylight: "Daylight",
    themeSage: "Sage",
    addDeadlineTitle: "Přidat termín",
    deadlineTitle: "Termín úkolu",
    saveSettings: "Uložit nastavení",
    minShort: "min",
    addTaskAria: "Přidat úkol",
    fullscreen: "Na celou obrazovku",
    fullscreenTitle: "Otevřít časovač na celou obrazovku",
    enterFullscreen: "Na celou obrazovku",
    exitFullscreen: "Ukončit celou obrazovku",
    close: "Zavřít",
    sessionsToday: "relací dnes",
    focusToday: "soustředění dnes",
    noTaskYet: "Nevybraný úkol"
  }
};

const FIREFLY_PALETTE = {
  // Midnight ("Moon"): pale cores over the deep violet, halos on the mode accent.
  midnight: {
    work: { core: "rgba(255, 230, 250, 1)", halo: "rgba(212, 95, 206, .64)", glow: "rgba(178, 50, 175, .72)" },
    shortBreak: { core: "rgba(214, 250, 255, 1)", halo: "rgba(79, 201, 224, .62)", glow: "rgba(40, 170, 196, .70)" },
    longBreak: { core: "rgba(232, 228, 255, 1)", halo: "rgba(154, 140, 242, .62)", glow: "rgba(116, 100, 224, .70)" }
  },
  // Daylight ("Twine"): the deepened hues — the pastels themselves vanish on pastel.
  daylight: {
    work: { core: "rgba(184, 74, 92, 1)", halo: "rgba(154, 54, 72, .55)", glow: "rgba(184, 74, 92, .48)" },
    shortBreak: { core: "rgba(60, 99, 200, 1)", halo: "rgba(44, 76, 168, .55)", glow: "rgba(60, 99, 200, .48)" },
    longBreak: { core: "rgba(147, 51, 165, 1)", halo: "rgba(118, 36, 134, .55)", glow: "rgba(147, 51, 165, .48)" }
  },
  // Sage: warm amber / emerald cores tuned to the green surface.
  sage: {
    work: { core: "rgba(255, 237, 190, 1)", halo: "rgba(245, 158, 11, .60)", glow: "rgba(217, 119, 6, .66)" },
    shortBreak: { core: "rgba(209, 250, 229, 1)", halo: "rgba(52, 211, 153, .60)", glow: "rgba(16, 185, 129, .66)" },
    longBreak: { core: "rgba(237, 233, 255, 1)", halo: "rgba(167, 139, 250, .60)", glow: "rgba(139, 92, 246, .66)" }
  }
};
